name:                euler
version:             0.1.0.0
github:              "githubuser/euler"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

dependencies:
- base >= 4.7 && < 5
executables:
  pasm:
    main:                24.hs
